apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-configuration
data:
  hazelcast.yaml: |-
    cluster-name: pnfs-community
    properties:
      hazelcast.discovery.enabled: false
      hazelcast.phone.home.enabled: false

    network:
      join:
        multicast:
          enabled: false
        tcp-ip:
          enabled: true
      rest-api:
        enabled: true
        endpoint-groups:
          HEALTH_CHECK:
            enabled: true

    cache:
      open-stateid:
        key-type:
          class-name: "[B"
        value-type:
          class-name: "[B"
        statistics-enabled: false
        management-enabled: false
        read-through: true
        write-through: true
        in-memory-format: BINARY
---

apiVersion: v1
kind: Service
metadata:
  name: hazelcast-service
spec:
  selector:
    app: hazelcast
  ports:
    - name: hazelcast
      port: 5701
      targetPort: 5701
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast
spec:
  selector:
    matchLabels:
      app: hazelcast
  replicas: 1
  serviceName: hazelcast-service
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      containers:
      - name: hazelcast
        image: hazelcast/hazelcast:4.1
        ports:
        - name: hazelcast
          containerPort: 5701
        livenessProbe:
          httpGet:
            path: /hazelcast/health/node-state
            port: 5701
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /hazelcast/health/node-state
            port: 5701
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - name: hazelcast-storage
          mountPath: /data/hazelcast
        env:
        - name: JAVA_OPTS
          value: "-Dhazelcast.config=/data/hazelcast/hazelcast.yaml"
      volumes:
      - name: hazelcast-storage
        configMap:
          name: hazelcast-configuration


