#
# pNFS MDS service
#
apiVersion: v1
kind: Service
metadata:
  name: nfs-mds
spec:
  selector:
    app: nfs-mds
  ports:
    - name: mds
      port: 2049
---

#
# pNFS MDS exposed service
#
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    name: nfs-mds
  name: nfs-mds-endpoint
subsets:
- addresses:
  - ip: 10.42.9.187
    nodeName: gest-k8s-test2
    targetRef:
      kind: Pod
      name: nfs-mds-0
  ports:
  - port: 2049
    protocol: TCP
---

#
# pNFS MDS server
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-mds
  labels:
    app.kubernetes.io/name: nfs-mds
spec:
  replicas: 1
  serviceName: pnfs-service
  selector:
    matchLabels:
      app: nfs-mds
  template:
    metadata:
      labels:
        app: nfs-mds
    spec:
      containers:
      - name: nfs-mds
        image: docker.io/dcache/pnfs-community:latest
        imagePullPolicy: Always
        command:
          - sh
          - -c
          - "/run.sh mds"
        ports:
        - name: nfs-mds
          containerPort: 2049
        volumeMounts:
        - name: nfs-storage
          mountPath: /pnfs/etc
        env:
        - name: ZOOKEEPER_CONNECT
          value: zk-0.zk-hs:2181,zk-1.zk-hs:2181,zk-2.zk-hs:2181
        - name: NFS_PORT
          value: "2049"
        - name: HAZELCAST_HOST
          value: hazelcast-0.hazelcast-service
      volumes:
      - name: nfs-storage
        configMap:
          name: nfs-configuration
