#
# A worker node
#

kind: Pod
apiVersion: v1
metadata:
  name: wn-with-nfs
spec:
  # Add the server as an NFS volume for the pod
  volumes:
    - name: nfs-volume
      nfs: 
        # URL for the NFS server
        server: 10.42.1.101
        path: /

  containers:
    - name: wn
      image: centos:8
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"

      volumeMounts:
        - name: nfs-volume
          mountPath: /var/nfs